project_id = "hqmkzfejbsgjbhadetst"

[functions.process-complaint]
verify_jwt = false

[functions.forward-ticket]
verify_jwt = false

[functions.parse-pdf-document]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false